[tool.black]
line-length = 120
exclude = '''
/(
  | migrations
)/
'''


[tool.ruff]
select = ["E", "F", "I"]
extend-exclude = ["migrations"]
force-exclude = true
line-length = 120


[tool.ruff.isort]
force-single-line = false
force-wrap-aliases = true
combine-as-imports = true
