[tool.black]
line-length = 120
exclude = '''
/(
  | migrations
)/
'''

[tool.ruff]
extend-exclude = ["migrations"]
force-exclude = true
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.isort]
force-single-line = false
force-wrap-aliases = true
combine-as-imports = true
