# Generated by Django 3.2.7 on 2021-12-10 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_scrapped', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('hexid', models.CharField(max_length=64)),
                ('language', models.CharField(default='Unknown', max_length=64)),
                ('date', models.DateField()),
                ('writeups_num', models.IntegerField(default=0)),
                ('comments_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Clear'), (1, 'Started'), (2, 'Aborted'), (3, 'Solved'), (4, 'Ignored')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='crackmes.task')),
            ],
        ),
    ]
