# Generated by Django 4.1.5 on 2023-01-25 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("heroes_version", models.IntegerField()),
                ("link", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="ActionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Clear"),
                            (1, "Started"),
                            (2, "Aborted"),
                            (3, "Completed"),
                            (4, "Ignored"),
                        ],
                        default=0,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions_heroes3maps",
                        to="heroes3maps.map",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_heroes3maps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
