# Generated by Django 4.1.5 on 2023-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes3maps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="link",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
