# Generated by Django 4.1.5 on 2023-01-30 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heroes3maps", "0002_alter_map_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="heroes_version",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(7),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
    ]
