# Generated by Django 4.2.2 on 2023-06-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("heroes3maps", "0005_alter_map_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_maps",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actionhistory",
            name="map",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="map_actions",
                to="heroes3maps.map",
            ),
        ),
        migrations.AlterField(
            model_name="actionhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_map_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="map",
            unique_together={("user", "name")},
        ),
    ]
