# Generated by Django 4.2.2 on 2023-06-18 17:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("heroes3maps", "0006_map_user_alter_actionhistory_map_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="map",
            unique_together={("user", "name", "heroes_version")},
        ),
    ]
