# Generated by Django 3.2.7 on 2022-01-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_appuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'permissions': [('special_access', 'Can have access to special trackers')]},
        ),
    ]
