# Generated by Django 3.2.6 on 2021-08-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comments',
            new_name='comments_num',
        ),
        migrations.RemoveField(
            model_name='task',
            name='link',
        ),
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.CharField(default='Unknown', max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='writeups_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
