# Generated by Django 3.2.6 on 2021-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackmes', '0002_auto_20210828_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
