# Generated by Django 3.2.6 on 2021-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackmes', '0003_alter_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('total_scrapped', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
