# Generated by Django 4.2.2 on 2023-06-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0003_alter_game_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionhistory",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_actions",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="actionhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
