# Generated by Django 4.2.2 on 2023-06-18 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("games", "0004_alter_actionhistory_game_alter_actionhistory_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name="game",
            unique_together={("user", "name")},
        ),
    ]
