# Generated by Django 3.2.7 on 2022-01-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'permissions': [('special_access', 'To have access to special trackers')]},
        ),
    ]
