# Generated by Django 4.2.2 on 2023-06-06 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_appuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
