name: 'Deploy to dokku'

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install linters
        run: |
          pip install -r requirements-dev.txt
      - name: Run linters
        run: |
          git diff-index --quiet HEAD -- .
          chmod +x ./lint.sh
          ./lint.sh lint

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.rivit.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./prod.Dockerfile
          push: true
          tags: registry.rivit.dev/ptb:latest
