name: 'Deploy to dokku'

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install linters
        run: |
          pip install -r requirements-dev.txt
      - name: Run linters
        run: |
          git diff-index --quiet HEAD -- .
          chmod +x ./lint.sh
          ./lint.sh lint

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: '--force'
          git_remote_url: ${{ secrets.DOKKU_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
